# choose device. if device < 0, so 'cpu' is chosen. Otherwise, it indicates gpu id 
device: 0

# log
logdir: logs/transformer/7  # the folder to save log

# train, test
run: test

# random seed
rand_seed: -1

# model config
num_devices: 1
model: maskgit
num_embeddings: 1024
embedding_dim: 256
lamda: 0.5
num_tokens: 256
n_layers: 12 # 12 if testing transformer
sample_temperature: 4.5
vqvae_path: ./vqvae_improved_epoch38.pth
start_epoch: 1

transformer_path: ./bitrans_tiny_imgnet_epoch50.pth


# dataset
root_dir: ./data/tiny-imagenet-200
filelist: ./datasets/filelist.txt
is_train: True
batch_size: 16 # 4: 32, 5: 16 6: 64
shuffle: True
learning_rate: 0.001
lr_step_size: 30
lr_gamma: 0.5
max_epochs: 50

transformer_test_dataset1: test1/
transformer_test_dataset2: test2/
vqvae_test_dataset1: vqvae_test1/
vqvae_test_dataset2: vqvae_test2/

disc_start: 10000

  
data:
  test: 
    root_dir: 
    filelist: 
    batch_size: 
    shuffle: False

# optimizer
optimizer: 
  type: adamw
  weight_decay: 0.01
  base_lr: 0.0001

# scheuler
scheduler:

